### ISSUE TITLE
Add option to rotate

### ISSUE THREAD

**Issue by fallais** [gen2brain/cam2ip#10]
Hello,

Nice software ! That could be nice to add an option to rotate (90 / 180 / 270) the image.
What do you think ?

**Comment by gen2brain** [comment]
It can be a useful option, I will add it these days, it should not be difficult to implement.

**Comment by fallais** [comment]
Oh thanks a lot !

**Comment by fallais** [comment]
Hello,
Did you find time to implement it ? :)

**Comment by gen2brain** [comment]
I am really busy currently, not sure when will I find time to implement rotate, but it is on my list.

**Comment by gen2brain** [comment]
Rotate option is added and new release binaries are uploaded.

**Comment by fallais** [comment]
Thanks, this is perfect !
