### ISSUE TITLE
[mpjpeg @ 0x7f3e844b0580] Expected boundary '--' not found, instead found a line of 20 bytes

### ISSUE THREAD

**Issue by Jsmilemsj** [gen2brain/cam2ip#16]
OpenCV3.4.3 prompts "[mpjpeg @ 0x7f3e844b0580] Expected boundary '--' not found, instead found a line of 20 bytes" when calling IP camera. Sometimes good, sometimes bad.

**Comment by gen2brain** [comment]
gocv now works with OpenCV 4.x, 3.x is not used anymore. Closing this one, feel free to open a new one if it happens also with the new version.
