### ISSUE TITLE
Cannot open more than 2 cameras on windows

### ISSUE THREAD

**Issue by pmnxt** [gen2brain/cam2ip#17]
When we try to open 3th camera we got:
camera: cannot open camera XX
All cameras are working when running 1 or 2 instances.
We use windows x64 (opencv_ffmpeg2413_64.dll). We use different ports and indexes.

**Comment by gen2brain** [comment]
So you are using OpenCV build right, and those are all same cameras/drivers? Did you try maybe with "native/no cgo" builds that use VideoForWindows?

**Comment by pmnxt** [comment]
Thanks for suggestions. 
Native version is not working for me, got the messages: cannot grab frame.
Cameras are the same, working on ispy.

**Comment by gen2brain** [comment]
Not sure then what is going on, never tried with multiple cameras. You can try to build cam2ip for OpenCV 3 or 4 (-tags cv3 ). Such build is not available for download, I can build it for you but I am very busy currently, not sure when will I find the time.

**Comment by pmnxt** [comment]
I think we have some workaround, thanks for help.
