### ISSUE TITLE
Please add LICENSE

### ISSUE THREAD

**Issue by RandomErrorMessage** [gen2brain/cam2ip#18]
Please add a license to your project. Without one it is legally questionable to work with your code. I recommend ISC for permissive license, or AGPL for a copyleft license.

**Comment by gen2brain** [comment]
There is already a license file and Github shows it properly, it is here https://github.com/gen2brain/cam2ip/blob/master/COPYING .

**Comment by RandomErrorMessage** [comment]
My mistake, how embarrassing ;)
