### ISSUE TITLE
 -

### ISSUE THREAD

**Issue by st3ffl0n** [gen2brain/cam2ip#29]

**Comment by gen2brain** [comment]
Hello,

The message is clear, there is no /dev/video0, what are your exact steps and device name? 
Btw. if static binary works and is just one file, not sure why insist on docker? In this case image is built from `scratch` so it is again just one binary, but usually you get the whole distro together with binary.

**Comment by st3ffl0n** [comment]
I want to use docker to make the stream available on my local network and also set a password

I unplugged my webcam, then:
ls -lha /dev/* > unplugged.txt 
plugged the webcam back in, then:
ls -lha /dev/* > plugged.txt
compare the devices to find the right name
vimdiff plugged.txt unplugged.txt

my device name is /dev/ttys001, but trying to run docker with this doesn't work
then I tried everything like device=/dev/ttys001:/dev/ttys001 ... device=/dev/video0:/dev/ttys001 ...
I alway get the same error message

**Comment by gen2brain** [comment]
Did you try with `--privileged` or `--network host`, maybe `--device=/dev:/dev`? Is that a USB or serial camera?

**Comment by st3ffl0n** [comment]
its a cheap usb camera https://www.amazon.de/gp/product/B08M99YWG9/ref=ppx_yo_dt_b_asin_title_o06_s00?ie=UTF8&psc=1

with `--privileged` it says "no camera at index 0" `docker run --privileged --device=/dev/ttys001:/dev/ttys001 -p56000:56000 -it gen2brain/cam2ip`

the other options don't work

**Comment by st3ffl0n** [comment]
I got it now working on a Raspberry pi. The only issue is that he doesn't recognise my .htpasswd path

I always get "stat gen2brain/cam2ip/htpasswd: no such file or directory"
I tried many path but don't seem to be able to find the base directory from which docker is looking

home/pi/Downloads/auth.htpasswd doesn't work.. 

Where do I have to put the file?
