### ISSUE TITLE
fatal error: jpeglib.h: No such file or directory - Windows 10 - How to install libjpeg-turbo

### ISSUE THREAD

**Issue by toom94** [gen2brain/cam2ip#48]
Hi,

I get an error when compiling on windows 10.

![image](https://github.com/gen2brain/cam2ip/assets/36904439/e0088469-51a6-4d47-8253-b77127d0eef4)

libjpeg-turbo installed
libjpeg-turbo-2.0.0-gcc.exe
path:
![image](https://github.com/gen2brain/cam2ip/assets/36904439/b7661487-08cc-4be0-bacf-dcfb794f8d4b)

I have no idea what's wrong, please help

**Comment by gen2brain** [comment]
Use `-tags jpeg` to build without CGO. Everything is in README, and you can search issues for many similar "issues".

**Comment by toom94** [comment]
--tags jpeg doesn't work for my camera. I need to build this with CV2. None of the previous issues solve my problem, please give me the correct instructions to install libjpeg-turbo on windows.

**Comment by gen2brain** [comment]
Sorry, I have no idea how to install something on Windows. I cross-compile from Linux. You are looking for general instructions, i.e. for MinGW, for msys, whatever you are using, or just install it anywhere and point CGO_CFLAGS/CGO_LDFLAGS. Basic C knowledge about compilation is required.

**Comment by gen2brain** [comment]
Btw. `-tags jpeg` has nothing to do with the camera, opencv or not. You can build with OpenCV and with `-tags jpeg`, i.e. native Go `image/jpeg` encoder.

**Comment by toom94** [comment]
-tags jpeg returns:

socket: read: camera: can not retrieve frame: EOF
![image](https://github.com/gen2brain/cam2ip/assets/36904439/e26b4ac6-6f2c-4723-8014-e9a6c4dd8ac2)

**Comment by toom94** [comment]
mam zainstalowane opencv w wersji  opencv-2.4.13

mam libjpeg-turbo w wersji: libjpeg-turbo-2.0.4-vc64.exe 

mama ustawione parametry go env:
![image](https://github.com/gen2brain/cam2ip/assets/36904439/e14cd1a2-efea-464e-974d-682fb8176ce7)


I have paths:
![image](https://github.com/gen2brain/cam2ip/assets/36904439/206c015d-f32c-4106-82c4-8860faa0550c)

**Comment by toom94** [comment]
ok, it worked, I built it with cv2 - but the application closes without any error... how can I find out the reason for closing?
![cloase_app](https://github.com/gen2brain/cam2ip/assets/36904439/6839cd24-6642-41d3-984b-3986346e9439)

**Comment by gen2brain** [comment]
Start the terminal first, and run it from terminal, so it stays when it crashes.

**Comment by toom94** [comment]
doesn't write anything
![image](https://github.com/gen2brain/cam2ip/assets/36904439/a97a1e0b-70b1-4080-a9c6-1fa57e9ced11)

**Comment by toom94** [comment]
I managed to get something more:
![image](https://github.com/gen2brain/cam2ip/assets/36904439/8ede6b7d-8f0d-4402-b293-e5397450272f)


Have you encountered such a problem?
