### ISSUE TITLE
Changing resolution Windows

### ISSUE THREAD

**Issue by Pepepele2** [gen2brain/cam2ip#54]
Hello,
I would ask for an instruction how to change resolution under Windows OS?

**Comment by gen2brain** [comment]
Do `-width` and `-height` options from README work?

**Comment by Pepepele2** [comment]
But where should I use it? The README file doeasn't explain a thing how to use this options with the .exe

**Comment by gen2brain** [comment]
You pass it like this `cam2ip.exe -width 640` or `--width`, similar to how every app that has options works. It would be too much to create examples and docs for that.  Similar to how you can just set the `CAM2IP_WIDTH` environment variable, of course, I will not explain what is ENV, this is not the place for that.

**Comment by Pepepele2** [comment]
But should i start it trough cmd or how to set this parameters?

**Comment by gen2brain** [comment]
Yes, you start it from cmd with options, or you can set the `CAM2IP_WIDTH` and `CAM2IP_HEIGHT` environment variables.

**Comment by Pepepele2** [comment]
Thank you very  much for the answer :)
